# Generated by Django 5.2.7 on 2025-10-16 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, unique=True)),
                ('clima', models.CharField(blank=True, max_length=200)),
                ('poblacion', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('año_nacimiento', models.CharField(blank=True, max_length=20)),
                ('genero', models.CharField(blank=True, max_length=50)),
                ('biografia', models.TextField(blank=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('mundo_origen', models.ForeignKey(blank=True, help_text='Planeta natal del personaje', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residentes', to='api.planeta')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Pelicula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('texto_de_apertura', models.TextField(blank=True, help_text='Opening crawl')),
                ('director', models.CharField(blank=True, max_length=200)),
                ('productores', models.TextField(blank=True, help_text='Lista de productores como texto o JSON simple')),
                ('fecha_estreno', models.DateField(blank=True, null=True)),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('personajes', models.ManyToManyField(blank=True, related_name='peliculas', to='api.personaje')),
                ('planetas', models.ManyToManyField(blank=True, related_name='peliculas', to='api.planeta')),
            ],
            options={
                'ordering': ['-fecha_estreno', 'titulo'],
            },
        ),
    ]
