# Generated by Django 5.2.7 on 2025-10-16 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaje',
            old_name='año_nacimiento',
            new_name='fecha_nacimiento',
        ),
    ]
